version: '3.4'

services:
  servicea:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  serviceb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

