version: '3.4'

services:
  servicea:
    image: ${DOCKER_REGISTRY-}servicea
    build:
      context: .
      dockerfile: ServiceA/Dockerfile

  serviceb:
    image: ${DOCKER_REGISTRY-}serviceb
    build:
      context: .
      dockerfile: ServiceB/Dockerfile

